export const GameState = 
{
    INITIATING: 'INITIATING',
    REQUESTING_MOVE: 'REQUESTING_MOVE',
    REQUESTED_MOVE: 'REQUESTED_MOVE',
    PROCESSING_MOVE: 'PROCESSING_MOVE',
    PROCESSED_MOVE: 'PROCESSED_MOVE',
    REQUESTING_SUGGESTION: 'REQUESTING_SUGGESTION',
    REQUESTED_SUGGESTION: 'REQUESTED_SUGGESTION',
    PROCESSING_SUGGESTION: 'PROCESSING_SUGGESTION',
    PROCESSED_SUGGESTION: 'PROCESSED_SUGGESTION',
    REQUESTING_PROOF: 'REQUESTING_PROOF',
    REQUESTED_PROOF: 'REQUESTED_PROOF',
    PROCESSING_PROOF: 'PROCESSING_PROOF',
    PROCESSED_PROOF: 'PROCESSED_PROOF',
    PROCESSED_ACCUSATION: 'PROCESSED_ACCUSATION',
    GAME_OVER: 'GAME_OVER'
};