export const GameState = {
    INITIATING: 'INITIATING',
    REQUESTING_MOVE: 'REQUESTING_MOVE',
    REQUESTED_MOVE: 'REQUESTED_MOVE',
    PROCESSING_MOVE: 'PROCESSING_MOVE',
    PROCESSED_MOVE: 'PROCESSED_MOVE'
};